application: ezqrcode
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /images
  static_dir: images

- url: /.*
  script: _go_app
